import loginElement from '../../support/loginElement'
const userDataLogin = require('../../fixtures/userDataLogin.json')
describe('Wish list', () => {
    it('Add To Wish list', () => {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit('https://magento.softwaretestingboard.com')
        cy.get('.panel > .header > .authorization-link > a').click()
        cy.get(loginElement.Uname).type(userDataLogin.inputUname)
        cy.get(loginElement.pass).type(userDataLogin.inputPass)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get('#ui-id-4 > :nth-child(2)').trigger('mouseover')
        cy.get('#ui-id-9').trigger('mouseover')
        cy.get('#ui-id-11 > span').click()
        cy.get(':nth-child(1) > .product-item-info > .photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
        cy.get('#option-label-size-143-item-167').click()
        cy.get('#option-label-color-93-item-49').click()
        cy.get('.product-addto-links > .towishlist').click()
        cy.get('.message-success')
        cy.contains('Olivia 1/4 Zip Light Jacket has been added to your Wish List. Click here to continue shopping.').should('exist')
    })

    it('View Wish list Page With Item', () => {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit('https://magento.softwaretestingboard.com')
        cy.get('.panel > .header > .authorization-link > a').click()
        cy.get(loginElement.Uname).type(userDataLogin.inputUname)
        cy.get(loginElement.pass).type(userDataLogin.inputPass)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > .link > a').click({force: true})
        cy.contains('My Wish List').should('exist')
        cy.contains('1 Item').should('exist')
    })  

    it('View Wish list Page Without Item', () => {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit('https://magento.softwaretestingboard.com')
        cy.get('.panel > .header > .authorization-link > a').click()
        cy.get(loginElement.Uname).type(userDataLogin.inputUname2)
        cy.get(loginElement.pass).type(userDataLogin.inputPass2)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > .link > a').click({force: true})
        cy.get('#wishlist-view-form > .message')
        cy.contains('You have no items in your wish list.').should('exist')
    })

    it('View Wish list Page With Item', () => {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit('https://magento.softwaretestingboard.com')
        cy.get('.panel > .header > .authorization-link > a').click()
        cy.get(loginElement.Uname).type(userDataLogin.inputUname)
        cy.get(loginElement.pass).type(userDataLogin.inputPass)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > .link > a').click({force: true})
        cy.get('.actions-secondary > .btn-remove').click()
        cy.get('.message-success')
        cy.contains("Olivia 1/4 Zip Light Jacket has been removed from your Wish List.").should('exist')
    })
    it('View wish list Page No Item', () => {
        cy.clearAllCookies()
        cy.clearAllLocalStorage()
        cy.visit('https://magento.softwaretestingboard.com')
        cy.get('.panel > .header > .authorization-link > a').click()
        cy.get(loginElement.Uname).type(userDataLogin.inputUname2)
        cy.get(loginElement.pass).type(userDataLogin.inputPass2)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click().click()
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > .link > a').click()
        cy.get('.actions-secondary > .btn-remove').should('not.exist')
        cy.get('#wishlist-view-form > .message').should("contain.text", "You have no items in your wish list")
    })
})
